import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Archive, CalendarDays, CheckCircle2, ChevronLeft, Circle, Copy, Plus, RotateCcw, Search, Sparkles, X } from 'lucide-react'
import './styles.css'

type ChecklistItem={id:string;title:string;completed:boolean;due_date?:string;owner?:string}
type Booking={id:string;reference:string;client_name:string;company?:string;event_name:string;brand:string;service:string;status:string;event_date:string;event_start?:string;event_end?:string;access_time?:string;setup_ready_by?:string;collection_time?:string;venue?:string;venue_address?:string;contact_phone?:string;contact_email?:string;notes?:string;checklist:ChecklistItem[];archived_at?:string|null}

const fmt=(d?:string)=>d?new Date(`${d}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—'

function App(){
 const [bookings,setBookings]=useState<Booking[]>([]),[selected,setSelected]=useState<Booking|null>(null),[query,setQuery]=useState(''),[showNew,setShowNew]=useState(false),[view,setView]=useState<'active'|'archived'>('active')
 useEffect(()=>{fetch('/api/bookings').then(r=>r.ok?r.json():Promise.reject()).then(v=>{if(Array.isArray(v))setBookings(v)}).catch(()=>{})},[])
 const activeBookings=useMemo(()=>bookings.filter(b=>!b.archived_at),[bookings])
 const archivedBookings=useMemo(()=>bookings.filter(b=>!!b.archived_at),[bookings])
 const base=view==='archived'?archivedBookings:activeBookings
 const filtered=useMemo(()=>base.filter(b=>[b.reference,b.client_name,b.company,b.event_name,b.service,b.venue].join(' ').toLowerCase().includes(query.toLowerCase())),[base,query])
 const tasks=activeBookings.flatMap(b=>b.checklist).filter(t=>!t.completed),today=new Date().toISOString().slice(0,10),overdue=tasks.filter(t=>t.due_date&&t.due_date<today)
 const save=async(b:Booking)=>{setBookings(p=>p.map(x=>x.id===b.id?b:x));setSelected(b);await fetch(`/api/bookings/${b.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(b)}).catch(()=>{})}
 const archiveToggle=async(b:Booking,archive:boolean)=>{const opts:RequestInit=archive?{method:'DELETE'}:{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({restore:true})};await fetch(`/api/bookings/${b.id}`,opts).catch(()=>{});setBookings(p=>p.map(x=>x.id===b.id?{...x,archived_at:archive?new Date().toISOString():null}:x));setSelected(null)}
 if(selected)return <BookingView booking={selected} onBack={()=>setSelected(null)} onSave={save} onArchiveToggle={archiveToggle}/>
 return <div className="shell"><aside><div className="logo"><b>Q</b><span><strong>Event CRM</strong><small>Event Operations</small></span></div><nav><button className={view==='active'?'active':''} onClick={()=>setView('active')}>Bookings</button><button className={view==='archived'?'active':''} onClick={()=>setView('archived')}>Archived</button><button>Tasks</button><button>Calendar</button><button>Templates</button><button>Settings</button></nav><div className="ai"><Sparkles size={18}/><span><strong>AI ready</strong><small>ChatGPT + Claude access layer</small></span></div></aside><main><header><div><h1>Bookings</h1><p>Your operational source of truth for every event.</p></div><button className="primary" onClick={()=>setShowNew(true)}><Plus size={18}/>New booking</button></header><section className="stats"><Stat label="Bookings" value={activeBookings.length}/><Stat label="Open tasks" value={tasks.length}/><Stat label="Overdue" value={overdue.length} danger/><Stat label="Next event" value={activeBookings[0]?fmt(activeBookings[0].event_date):'—'}/></section><section className="panel"><div className="panelHead"><div><h2>{view==='archived'?'Archived bookings':'Booking register'}</h2><p>{view==='archived'?'Completed events that have been archived — open one to restore it.':'Search client, service, venue or booking number.'}</p></div><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search bookings…"/></label></div><div className="table"><div className="row head"><span>Event</span><span>Service</span><span>Date</span><span>Progress</span><span>Status</span></div>{filtered.length===0&&<p className="empty">{view==='archived'?'No archived bookings yet.':'No bookings match your search.'}</p>}{filtered.map(b=>{const done=b.checklist.filter(x=>x.completed).length,pct=b.checklist.length?Math.round(done/b.checklist.length*100):0;return <button className="row booking" key={b.id} onClick={()=>setSelected(b)}><span><strong>{b.event_name}</strong><small>{b.reference} · {b.client_name}</small></span><span>{b.service}<small>{b.brand}</small></span><span>{fmt(b.event_date)}</span><span><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{done}/{b.checklist.length} · {pct}%</small></span><span><em>{b.status}</em></span></button>})}</div></section>{showNew&&<NewBooking onClose={()=>setShowNew(false)} onCreate={b=>{setBookings(p=>[b,...p]);setShowNew(false);setSelected(b)}}/>}</main></div>
}
function Stat({label,value,danger=false}:{label:string;value:string|number;danger?:boolean}){return <div className={`stat ${danger?'danger':''}`}><small>{label}</small><strong>{value}</strong></div>}
function BookingView({booking,onBack,onSave,onArchiveToggle}:{booking:Booking;onBack:()=>void;onSave:(b:Booking)=>void;onArchiveToggle:(b:Booking,archive:boolean)=>void}){const [b,setB]=useState(booking),done=b.checklist.filter(x=>x.completed).length,pct=b.checklist.length?Math.round(done/b.checklist.length*100):0;const update=(next:Booking)=>{setB(next);onSave(next)};const add=()=>{const title=prompt('Task name');if(title)update({...b,checklist:[...b.checklist,{id:crypto.randomUUID(),title,completed:false}]})};const archived=!!b.archived_at;const toggleArchive=()=>{if(archived){if(confirm('Restore this booking to active bookings?'))onArchiveToggle(b,false)}else{if(confirm('Archive this booking? It will move out of the active list, and can be restored later from the Archived section.'))onArchiveToggle(b,true)}};return <div className="detail"><div className="detailTop"><button onClick={onBack}><ChevronLeft size={18}/>Bookings</button><button onClick={()=>navigator.clipboard.writeText(`${location.origin}/bookings/${b.id}`)}><Copy size={16}/>Copy Outlook link</button><button className={archived?'restore':'archive'} onClick={toggleArchive}>{archived?<RotateCcw size={16}/>:<Archive size={16}/>}{archived?'Restore booking':'Archive booking'}</button></div><div className="detailBody"><div className="title"><div><small>{b.reference} · {b.brand}</small><h1>{b.event_name}</h1><p>{b.client_name}{b.company?` · ${b.company}`:''}</p></div><em>{b.status}</em>{archived&&<em className="archivedBadge">Archived</em>}</div><div className="detailGrid"><section className="panel card"><h2>Event details</h2><div className="details"><Field label="Date" value={fmt(b.event_date)}/><Field label="Live times" value={`${b.event_start||'—'} ${b.event_end?`– ${b.event_end}`:''}`}/><Field label="Access" value={b.access_time||'—'}/><Field label="Ready by" value={b.setup_ready_by||'—'}/><Field label="Venue" value={b.venue||'—'}/><Field label="Service" value={b.service}/></div><label>Booking notes<textarea value={b.notes||''} onChange={e=>setB({...b,notes:e.target.value})} onBlur={()=>onSave(b)} placeholder="Operational notes, access, artwork, client requests…"/></label></section><section className="panel card"><div className="checkHead"><div><h2>Delivery checklist</h2><p>{done} of {b.checklist.length} complete</p></div><strong>{pct}%</strong></div><div className="bigProgress"><i style={{width:`${pct}%`}}/></div>{b.checklist.map(c=><div className={`task ${c.completed?'done':''}`} key={c.id}><button onClick={()=>update({...b,checklist:b.checklist.map(x=>x.id===c.id?{...x,completed:!x.completed}:x)})}>{c.completed?<CheckCircle2/>:<Circle/>}</button><span><strong>{c.title}</strong><small>{c.owner||'Unassigned'}{c.due_date?` · due ${fmt(c.due_date)}`:''}</small></span></div>)}<button className="add" onClick={add}><Plus size={16}/>Add checklist item</button></section></div></div></div>}
function Field({label,value}:{label:string;value:string}){return <div className="field"><CalendarDays size={17}/><span><small>{label}</small><strong>{value}</strong></span></div>}
function NewBooking({onClose,onCreate}:{onClose:()=>void;onCreate:(b:Booking)=>void}){const [f,setF]=useState({event_name:'',client_name:'',company:'',brand:'Quirky Hire',service:'',event_date:'',venue:''});const create=async()=>{const b:Booking={...f,id:crypto.randomUUID(),reference:`QH-${new Date().getFullYear()}-${Math.floor(1000+Math.random()*9000)}`,status:'Confirmed',checklist:[{id:crypto.randomUUID(),title:'Booking details checked',completed:false,owner:'Admin'},{id:crypto.randomUUID(),title:'Client requirements confirmed',completed:false,owner:'Admin'},{id:crypto.randomUUID(),title:'Artwork / branding approved',completed:false,owner:'Design'},{id:crypto.randomUUID(),title:'Equipment and stock allocated',completed:false,owner:'Ops'},{id:crypto.randomUUID(),title:'Pre-event equipment test complete',completed:false,owner:'Ops'},{id:crypto.randomUUID(),title:'Vehicle load checked',completed:false,owner:'Ops'}]};try{const r=await fetch('/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});if(r.ok)return onCreate(await r.json())}catch{}onCreate(b)};return <div className="modalWrap"><div className="modal"><button className="x" onClick={onClose}><X/></button><small>NEW BOOKING</small><h2>Create event record</h2><div className="form">{(['event_name','client_name','company','service','event_date','venue'] as const).map(k=><label key={k}>{k.replaceAll('_',' ')}<input type={k==='event_date'?'date':'text'} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<label>Brand<select value={f.brand} onChange={e=>setF({...f,brand:e.target.value})}><option>Quirky Hire</option><option>Photobooths London</option><option>Brand Experience Partner</option></select></label></div><div className="actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={create}>Create booking</button></div></div></div>}
createRoot(document.getElementById('root')!).render(<App/>)
